version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.13

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-v1

      - run:
          name: Install Python dependencies
          command: |
            pip install --upgrade --user pip
            pip install --user -r build_requirements.txt
            pip list

      - save_cache:
          key: pip-cache-v1
          paths:
            - ~/.cache/pip

      - run:
          name: Build docs
          command: |
            # NOTE: bad interaction w/ blas multithreading on circleci
            export OMP_NUM_THREADS=1
            make web  # FIX: check that failing examples produce failure

      - store_artifacts:
          path: _build/html
